_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

evt_api_home:
    resource: EVT\ApiBundle\Controller\DefaultController 
    prefix:   /
    schemes:  [http]

evt_api:
    resource: "@EVTApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/
    schemes:  [http]