services:
    evt.api_key.user_provider:
        class: EVT\ApiBundle\Security\ApiKeyUserProvider
        arguments: [%evt_api.apikeys%]

    evt.api_key.authenticator:
        class:     EVT\ApiBundle\Security\ApiKeyAuthenticator
        arguments: [@evt.api_key.user_provider]

    evt.factory.lead:
        class:     EVT\ApiBundle\Factory\LeadFactory
        arguments: [@evt.repository.showroom, @evt.repository.lead]

    evt.factory.user:
        class:     EVT\ApiBundle\Factory\UserFactory
