services:
    evt.api_key.user_provider:
        class: EVT\ApiBundle\Security\ApiKeyUserProvider
        arguments: [%evt_api.apikeys%]

    evt.api_key.authenticator:
        class:     EVT\ApiBundle\Security\ApiKeyAuthenticator
        arguments: [@evt.api_key.user_provider]

    evt.factory.lead:
        class:     EVT\ApiBundle\Factory\LeadFactory
        arguments: [@evt.repository.showroom, @evt.repository.lead, @logger]
        tags:
            - { name: monolog.logger, channel: lead }
    evt.factory.user:
        class:     EVT\ApiBundle\Factory\UserFactory
        
    evt.factory.provider:
        class:     EVT\ApiBundle\Factory\ProviderFactory
        arguments: [@evt.repository.provider, @evt.repository.user]

    api.monolog.json_formatter:
        class: Monolog\Formatter\JsonFormatter

    api.monitor.check.leads:
        class: EVT\ApiBundle\Check\LeadsEndpointCheck
        arguments: ["%kernel.logs_dir%/leads.%kernel.environment%.log"]
        tags:
           - { name: liip_monitor.check}

    evt.factory.showroom:
        class:     EVT\ApiBundle\Factory\ShowroomFactory
        arguments: 
            - @evt.repository.vertical
            - @evt.repository.provider
            - @evt.repository.showroom
            - @old_sound_rabbit_mq.emd_showroom_created_producer
            - @jms_serializer
